-- TERA first-party visitor and successful-compilation counters.
-- Run this once in the Supabase SQL editor, then set SUPABASE_URL and
-- SUPABASE_SECRET_KEY only on the server host. Never put the secret in HTML.

create extension if not exists pgcrypto;

create table if not exists public.tera_visitors (
  id uuid primary key default gen_random_uuid(),
  display_name text,
  country_code text not null check (country_code ~ '^[A-Z]{2}$'),
  notice_version text not null default '2026-08-14',
  created_at timestamptz not null default now(),
  constraint tera_display_name_length check (
    display_name is null or char_length(display_name) between 2 and 32
  )
);

create table if not exists public.tera_usage_events (
  id bigint generated by default as identity primary key,
  visitor_id uuid references public.tera_visitors(id) on delete set null,
  booklet_count integer not null check (booklet_count between 1 and 100),
  source_pages integer not null check (source_pages between 1 and 100000),
  output_pages integer not null check (output_pages between 1 and 100000),
  pages_avoided integer not null check (pages_avoided >= 0),
  created_at timestamptz not null default now(),
  constraint tera_page_math check (
    pages_avoided = greatest(source_pages - output_pages, 0)
  )
);

create index if not exists tera_visitors_created_at_idx
  on public.tera_visitors(created_at desc);
create index if not exists tera_usage_events_created_at_idx
  on public.tera_usage_events(created_at desc);
create index if not exists tera_usage_events_visitor_id_idx
  on public.tera_usage_events(visitor_id);

alter table public.tera_visitors enable row level security;
alter table public.tera_usage_events enable row level security;

revoke all on table public.tera_visitors from anon, authenticated;
revoke all on table public.tera_usage_events from anon, authenticated;

create or replace function public.tera_get_public_stats()
returns jsonb
language plpgsql
volatile
security definer
set search_path = public
as $$
begin
  -- Keep a short-lived human-readable field, then preserve only coarse metrics.
  update public.tera_visitors
    set display_name = null
    where display_name is not null and created_at < now() - interval '90 days';

  -- Public totals are a rolling 24-month window, not permanent profiles.
  delete from public.tera_usage_events
    where created_at < now() - interval '24 months';
  delete from public.tera_visitors
    where created_at < now() - interval '24 months';

  return (
    select jsonb_build_object(
      'visitorCount', (select count(*) from public.tera_visitors),
      'compilationCount', (select coalesce(sum(booklet_count), 0) from public.tera_usage_events),
      'pagesAvoided', (select coalesce(sum(pages_avoided), 0) from public.tera_usage_events),
      'countryCount', (
        select count(distinct country_code)
        from public.tera_visitors
        where country_code <> 'ZZ'
      )
    )
  );
end;
$$;

revoke all on function public.tera_get_public_stats() from public, anon, authenticated;
grant execute on function public.tera_get_public_stats() to service_role;
